# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_mnist": "00_data.ipynb",
         "MovingMNIST": "00_data.ipynb",
         "ImageSeq": "00_data.ipynb",
         "ImageTupleTransform": "00_data.ipynb",
         "AddCoords": "01_models.conv_rnn.ipynb",
         "CoordConv": "01_models.conv_rnn.ipynb",
         "ConvGRU_cell": "01_models.conv_rnn.ipynb",
         "TimeDistributed": "01_models.conv_rnn.ipynb",
         "Encoder": "02_models.transformer.ipynb",
         "UpsampleBlock": "01_models.conv_rnn.ipynb",
         "Decoder": "01_models.conv_rnn.ipynb",
         "StackUnstack": "01_models.conv_rnn.ipynb",
         "SimpleModel": "01_models.conv_rnn.ipynb",
         "StackLoss": "01_models.conv_rnn.ipynb",
         "MultiImageDice": "01_models.conv_rnn.ipynb",
         "DCN": "02_models.dcn.ipynb",
         "DETR": "02_models.transformer.ipynb",
         "detr_split": "02_models.transformer.ipynb",
         "TransformerTS": "02_models.transformer.ipynb",
         "tf_split": "02_models.transformer.ipynb",
         "VGGBlock": "02_tcn.ipynb",
         "VGG": "02_tcn.ipynb",
         "Chomp1d": "02_tcn.ipynb",
         "TemporalBlock3D": "02_tcn.ipynb",
         "TemporalConvNet3D": "02_tcn.ipynb",
         "TCN3D": "02_tcn.ipynb",
         "SimpleTCN": "02_tcn.ipynb",
         "SimpleTCN2": "02_tcn.ipynb",
         "PhyCell_Cell": "03_phy_original.ipynb",
         "PhyCell": "03_phy_original.ipynb",
         "ConvLSTM_Cell": "03_phy_original.ipynb",
         "ConvLSTM": "03_phy_original.ipynb",
         "dcgan_conv": "04_seq2seq.ipynb",
         "dcgan_upconv": "04_seq2seq.ipynb",
         "image_encoder": "04_seq2seq.ipynb",
         "image_decoder": "04_seq2seq.ipynb",
         "EncoderRNN": "03_phy_original.ipynb",
         "M2K": "03_phy_original.ipynb",
         "K2M": "03_phy_original.ipynb",
         "tensordot": "03_phy_original.ipynb",
         "PhyDNet": "03_phy_original.ipynb",
         "ConvGRUCell": "04_seq2seq.ipynb",
         "ConvGRU": "04_seq2seq.ipynb",
         "Seq2Seq": "04_seq2seq.ipynb",
         "Seq2SeqPhy": "04_seq2seq.ipynb",
         "EncoderLoss": "04_seq2seq.ipynb",
         "TeacherForcing": "04_seq2seq.ipynb"}

modules = ["data.py",
           "models/conv_rnn.py",
           "models/dcn.py",
           "models/transformer.py",
           "models/tcn.py",
           "models/phy.py",
           "models/phy_original.py",
           "models/seq2seq.py"]

doc_url = "https://tcapelle.github.io/moving_mnist/"

git_url = "https://github.com/tcapelle/moving_mnist/tree/master/"

def custom_doc_links(name): return None
