# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ROOT_PATH": "00_data.ipynb",
         "DATA_PATH": "00_data.ipynb",
         "load_mnist": "00_data.ipynb"}

modules = ["data.py"]

doc_url = "https://tcapelle.github.io/moving_mnist/"

git_url = "https://github.com/tcapelle/moving_mnist/tree/master/"

def custom_doc_links(name): return None
