# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ROOT_PATH": "00_data.ipynb",
         "DATA_PATH": "00_data.ipynb",
         "load_mnist": "00_data.ipynb",
         "MovingMNIST": "00_data.ipynb",
         "ImageSeq": "00_data.ipynb",
         "ImageTupleTransform": "00_data.ipynb",
         "ConvGRU_cell": "01_models.conv_rnn.ipynb",
         "TimeDistributed": "01_models.conv_rnn.ipynb",
         "Encoder": "01_models.conv_rnn.ipynb",
         "UpsampleBlock": "01_models.conv_rnn.ipynb",
         "Decoder": "01_models.conv_rnn.ipynb",
         "SimpleModel": "01_models.conv_rnn.ipynb"}

modules = ["data.py",
           "models/conv_rnn.py"]

doc_url = "https://tcapelle.github.io/moving_mnist/"

git_url = "https://github.com/tcapelle/moving_mnist/tree/master/"

def custom_doc_links(name): return None
