# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_data.ipynb (unless otherwise specified).

__all__ = ['ROOT_PATH', 'DATA_PATH', 'load_mnist']

# Cell
ROOT_PATH = Path.cwd().parent
DATA_PATH = Path.cwd().parent/'data'

# Cell
def load_mnist():
    "Load MNIST dataset for generating training data"
    path = DATA_PATH/'train_images.gz'
    with gzip.open(path, 'rb') as f:
        mnist = np.frombuffer(f.read(), np.uint8, offset=16)
        mnist = mnist.reshape(-1, 28, 28)
    return mnist